version: '2'

services:
  
  elasticsearch_exporter:
    image: justwatch/elasticsearch_exporter:1.0.1 
    ports:
        - "0.0.0.0:9108:9108"
    network_mode: "host"
    command:
        - '-es.uri=http://localhost:9200'
    restart: always

